export const keyCode = [
  { label: "NONE", value: 0x00 },

  { label: "A", value: 0x04 },
  { label: "B", value: 0x05 },
  { label: "C", value: 0x06 },
  { label: "D", value: 0x07 },
  { label: "E", value: 0x08 },
  { label: "F", value: 0x09 },
  { label: "G", value: 0x0a },
  { label: "H", value: 0x0b },
  { label: "I", value: 0x0c },
  { label: "J", value: 0x0d },
  { label: "K", value: 0x0e },
  { label: "L", value: 0x0f },
  { label: "M", value: 0x10 },
  { label: "N", value: 0x11 },
  { label: "O", value: 0x12 },
  { label: "P", value: 0x13 },
  { label: "Q", value: 0x14 },
  { label: "R", value: 0x15 },
  { label: "S", value: 0x16 },
  { label: "T", value: 0x17 },
  { label: "U", value: 0x18 },
  { label: "V", value: 0x19 },
  { label: "W", value: 0x1a },
  { label: "X", value: 0x1b },
  { label: "Y", value: 0x1c },
  { label: "Z", value: 0x1d },

  { label: "1", value: 0x1e },
  { label: "2", value: 0x1f },
  { label: "3", value: 0x20 },
  { label: "4", value: 0x21 },
  { label: "5", value: 0x22 },
  { label: "6", value: 0x23 },
  { label: "7", value: 0x24 },
  { label: "8", value: 0x25 },
  { label: "9", value: 0x26 },
  { label: "0", value: 0x27 },

  { label: "ENTER", value: 0x28 },
  { label: "ESC", value: 0x29 },
  { label: "BACKSPACE", value: 0x2a },
  { label: "TAB", value: 0x2b },
  { label: "SPACE", value: 0x2c },
  { label: "MINUS", value: 0x2d },
  { label: "EQUAL", value: 0x2e },
  { label: "LEFTBRACE", value: 0x2f },
  { label: "RIGHTBRACE", value: 0x30 },
  { label: "BACKSLASH", value: 0x31 },
  { label: "HASHTILDE", value: 0x32 },
  { label: "SEMICOLON", value: 0x33 },
  { label: "APOSTROPHE", value: 0x34 },
  { label: "GRAVE", value: 0x35 },
  { label: "COMMA", value: 0x36 },
  { label: "DOT", value: 0x37 },
  { label: "SLASH", value: 0x38 },
  { label: "CAPSLOCK", value: 0x39 },

  { label: "F1", value: 0x3a },
  { label: "F2", value: 0x3b },
  { label: "F3", value: 0x3c },
  { label: "F4", value: 0x3d },
  { label: "F5", value: 0x3e },
  { label: "F6", value: 0x3f },
  { label: "F7", value: 0x40 },
  { label: "F8", value: 0x41 },
  { label: "F9", value: 0x42 },
  { label: "F10", value: 0x43 },
  { label: "F11", value: 0x44 },
  { label: "F12", value: 0x45 },

  { label: "SYSRQ", value: 0x46 },
  { label: "SCROLLLOCK", value: 0x47 },
  { label: "PAUSE", value: 0x48 },
  { label: "INSERT", value: 0x49 },
  { label: "HOME", value: 0x4a },
  { label: "PAGEUP", value: 0x4b },
  { label: "DELETE", value: 0x4c },
  { label: "END", value: 0x4d },
  { label: "PAGEDOWN", value: 0x4e },
  { label: "RIGHT", value: 0x4f },
  { label: "LEFT", value: 0x50 },
  { label: "DOWN", value: 0x51 },
  { label: "UP", value: 0x52 },

  { label: "NUMLOCK", value: 0x53 },
  { label: "KPSLASH", value: 0x54 },
  { label: "KPASTERISK", value: 0x55 },
  { label: "KPMINUS", value: 0x56 },
  { label: "KPPLUS", value: 0x57 },
  { label: "KPENTER", value: 0x58 },
  { label: "KP1", value: 0x59 },
  { label: "KP2", value: 0x5a },
  { label: "KP3", value: 0x5b },
  { label: "KP4", value: 0x5c },
  { label: "KP5", value: 0x5d },
  { label: "KP6", value: 0x5e },
  { label: "KP7", value: 0x5f },
  { label: "KP8", value: 0x60 },
  { label: "KP9", value: 0x61 },
  { label: "KP0", value: 0x62 },
  { label: "KPDOT", value: 0x63 },

  { label: "102ND", value: 0x64 },
  { label: "COMPOSE", value: 0x65 },
  { label: "POWER", value: 0x66 },
  { label: "KPEQUAL", value: 0x67 },

  { label: "F13", value: 0x68 },
  { label: "F14", value: 0x69 },
  { label: "F15", value: 0x6a },
  { label: "F16", value: 0x6b },
  { label: "F17", value: 0x6c },
  { label: "F18", value: 0x6d },
  { label: "F19", value: 0x6e },
  { label: "F20", value: 0x6f },
  { label: "F21", value: 0x70 },
  { label: "F22", value: 0x71 },
  { label: "F23", value: 0x72 },
  { label: "F24", value: 0x73 },

  { label: "OPEN", value: 0x74 },
  { label: "HELP", value: 0x75 },
  { label: "PROPS", value: 0x76 },
  { label: "FRONT", value: 0x77 },
  { label: "STOP", value: 0x78 },
  { label: "AGAIN", value: 0x79 },
  { label: "UNDO", value: 0x7a },
  { label: "CUT", value: 0x7b },
  { label: "COPY", value: 0x7c },
  { label: "PASTE", value: 0x7d },
  { label: "FIND", value: 0x7e },
  { label: "MUTE", value: 0x7f },
  { label: "VOLUMEUP", value: 0x80 },
  { label: "VOLUMEDOWN", value: 0x81 },

  { label: "KPCOMMA", value: 0x85 },

  { label: "RO", value: 0x87 },
  { label: "KATAKANAHIRAGANA", value: 0x88 },
  { label: "YEN", value: 0x89 },
  { label: "HENKAN", value: 0x8a },
  { label: "MUHENKAN", value: 0x8b },
  { label: "KPJPCOMMA", value: 0x8c },

  { label: "HANGEUL", value: 0x90 },
  { label: "HANJA", value: 0x91 },
  { label: "KATAKANA", value: 0x92 },
  { label: "HIRAGANA", value: 0x93 },
  { label: "ZENKAKUHANKAKU", value: 0x94 },

  { label: "KPLEFTPAREN", value: 0xb6 },
  { label: "KPRIGHTPAREN", value: 0xb7 },

  { label: "LEFTCTRL", value: 0xe0 },
  { label: "LEFTSHIFT", value: 0xe1 },
  { label: "LEFTALT", value: 0xe2 },
  { label: "LEFTMETA", value: 0xe3 },

  { label: "RIGHTCTRL", value: 0xe4 },
  { label: "RIGHTSHIFT", value: 0xe5 },
  { label: "RIGHTALT", value: 0xe6 },
  { label: "RIGHTMETA", value: 0xe7 },

  { label: "MOUSE_WHEELUP", value: 0xe8 },
  { label: "MOUSE_WHEELDOWN", value: 0xe9 },
  { label: "MOUSE_LEFT", value: 0xea },
  { label: "MOUSE_RIGHT", value: 0xeb },
  { label: "MOUSE_MIDDLE", value: 0xec },
  { label: "MOUSE_FAST", value: 0xed },
];

